# Matrices in `R`
- Vector is a 1D array of data elements of same data type.
- Matrix is a 2D array of data elements of same data type. 

In [4]:
m.a <- matrix(1:15, nrow = 3, ncol = 5)
print(m)


     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15


In [10]:
m.b <- matrix(1:15, nrow = 5)
print(m)


     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15


In [9]:
m.c <- matrix(1:15, nrow = 3, ncol = 5, byrow = TRUE)
print(m.c)


     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]   11   12   13   14   15


In [12]:
m <- matrix(1:3, nrow = 2, ncol = 3)
print(m)


     [,1] [,2] [,3]
[1,]    1    3    2
[2,]    2    1    3


In [13]:
m <- matrix(1:4, nrow = 2, ncol = 3)
print(m)


Warning message in matrix(1:4, nrow = 2, ncol = 3):
"data length [4] is not a sub-multiple or multiple of the number of columns [3]"


     [,1] [,2] [,3]
[1,]    1    3    1
[2,]    2    4    2


### Another way to create a matrix.
- rbind()
- cbind()
- These are very handy in some situation.
- We can create new and modify existing matrices. 

In [23]:

rb_matrix <- rbind(1:5, 6:10, 11:15)
print(rb_matrix)


     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]   11   12   13   14   15


In [24]:
cb_matrix <- cbind(1:5, 6:10, 11:15)
print(cb_matrix)

     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15


In [53]:
m <- matrix(1:25, nrow=5)
print(m)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25


In [29]:
print(cbind(m, 1:5))

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    6   11   16   21    1
[2,]    2    7   12   17   22    2
[3,]    3    8   13   18   23    3
[4,]    4    9   14   19   24    4
[5,]    5   10   15   20   25    5


In [30]:
print(rbind(m, 1:5))

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25
[6,]    1    2    3    4    5


In [45]:
num <-  matrix(1:15, ncol=3)
char<- matrix(LETTERS[1:15], ncol=3)
print(num)
print(char)

     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15
     [,1] [,2] [,3]
[1,] "A"  "F"  "K" 
[2,] "B"  "G"  "L" 
[3,] "C"  "H"  "M" 
[4,] "D"  "I"  "N" 
[5,] "E"  "J"  "O" 


In [47]:
print(cbind(num,char))

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] "1"  "6"  "11" "A"  "F"  "K" 
[2,] "2"  "7"  "12" "B"  "G"  "L" 
[3,] "3"  "8"  "13" "C"  "H"  "M" 
[4,] "4"  "9"  "14" "D"  "I"  "N" 
[5,] "5"  "10" "15" "E"  "J"  "O" 


In [48]:
print(rbind(num,char))

      [,1] [,2] [,3]
 [1,] "1"  "6"  "11"
 [2,] "2"  "7"  "12"
 [3,] "3"  "8"  "13"
 [4,] "4"  "9"  "14"
 [5,] "5"  "10" "15"
 [6,] "A"  "F"  "K" 
 [7,] "B"  "G"  "L" 
 [8,] "C"  "H"  "M" 
 [9,] "D"  "I"  "N" 
[10,] "E"  "J"  "O" 


### Naming a Matrix
- rownames()
- colnames()
- matrix(dimnames)

In [33]:
rownames(m) <- c("r1", "r2", "r3", "r4", "r5")
print(m)


   [,1] [,2] [,3] [,4] [,5]
r1    1    6   11   16   21
r2    2    7   12   17   22
r3    3    8   13   18   23
r4    4    9   14   19   24
r5    5   10   15   20   25


In [34]:
colnames(m) <- c("c1", "c2", "c3", "c4", "c5")
print(m)


   c1 c2 c3 c4 c5
r1  1  6 11 16 21
r2  2  7 12 17 22
r3  3  8 13 18 23
r4  4  9 14 19 24
r5  5 10 15 20 25


In [37]:
n <- matrix(1:15, nrow=5, byrow=T,
            dimnames = list(c("r1","r2","r3","r4","r5"),
                            c("c1","c2","c3")))
print(n)

   c1 c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9
r4 10 11 12
r5 13 14 15


## Getting values

Remeber that your are dealing with a two dimentional data structure so things may get complicated at a certain level.

In [59]:
m <- matrix(1:36, nrow=6, byrow=TRUE,
            dimnames=list(c("r1","r2","r3","r4","r5","r6"),
                          c("c1","c2","c3","c4","c5","c6")))
print(m)

   c1 c2 c3 c4 c5 c6
r1  1  2  3  4  5  6
r2  7  8  9 10 11 12
r3 13 14 15 16 17 18
r4 19 20 21 22 23 24
r5 25 26 27 28 29 30
r6 31 32 33 34 35 36


In [95]:
#Selecting one element.
# m[1,6] # 1row, 6column 
# m[2,5] # 2row, 5column 
# m[3,4] # 3row, 4column
m[7]     # Go element by element COLUMN wise.



[1] 2

In [109]:
# Selecting one Row or one Column.

# print(m[1,])     # select 1 row.
# print(m[1, 1:6]) # select 1 row.

# print(m[,1])     # select 1 column
# print(m[1, 1:6]) # select 1 row.

   c1 c2 c3 c4 c5 c6
r1  1  2  3  4  5  6
r2  7  8  9 10 11 12


In [119]:
# Selecting multiple Rows and multiple Columns.
# m
print(m[1, 1:6])

c1 c2 c3 c4 c5 c6 
 1  2  3  4  5  6 


In [73]:
# A fact.
is.matrix(m[3,1:6])
is.vector(class(m[3,1:6]))

[1] FALSE

[1] TRUE

In [130]:
# Selecting values of your choice instead of whole row or a whole column

# print(m[1,c(1,3,6)]      # select 1,3,5 rows with all columns
m[c(1,3,5),]               # select 1,3,5 rows with all columns
m[c("r1","r3","r5"),] 

c1 c2 c3 c4 c5 c6
r1  1  2  3  4  5  6
r3 13 14 15 16 17 18
r5 25 26 27 28 29 30

c1 c2 c3 c4 c5 c6
r1  1  2  3  4  5  6
r3 13 14 15 16 17 18
r5 25 26 27 28 29 30

## Matrix Arithimetic

In [137]:
a <- matrix(1:15,nrow=5, byrow=TRUE)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12  
[5,] 13   14   15

In [149]:
a - 16

[,1] [,2] [,3]
[1,] -15  -14  -13 
[2,] -12  -11  -10 
[3,]  -9   -8   -7 
[4,]  -6   -5   -4 
[5,]  -3   -2   -1